services:
  serviceA:
    image: build-test-platform-a:test
    build:
      context: .
      args:
        - SERVICENAME=serviceA
      platforms:
        - linux/amd64
        - linux/arm64
  serviceB:
    image: build-test-platform-b:test
    build:
      context: .
      args:
        - SERVICENAME=serviceB
      platforms:
        - linux/386
        - linux/arm64
  serviceC:
    image: build-test-platform-c:test
    build:
      context: .
      args:
        - SERVICENAME=serviceC
      platforms:
        - linux/amd64
        - linux/arm64